Public Class Hidden_
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        Dim DuTbl As New DataTable
        Dim ggggg = Format(My.Settings.MailTime, "HH:mm")

        If Format(Now, "HH:mm") = Format(My.Settings.MailTime, "HH:mm") Then
            If GetTbl("select [Sql] ,[ItemNm] ,[Details]  ,[DuDate]  ,[Wdays]  ,[To_]  ,[CC_] ,[LstSend],[Ignore] from main 
                                     where( main.Ignore = 0 or main.Ignore is null )  and Cast( main.DuDate - getdate()as smallint) <= Wdays", DuTbl) = Nothing Then
                If DuTbl.Rows.Count > 0 Then
                    For YY = 0 To DuTbl.Rows.Count - 1
                        Dim ggggddg = Int(DuTbl.Rows(YY).Item("DuDate").Subtract(Now).TotalDays)
                        Dim BdyStrt As String
                        Dim BdyEnd As String
                        Mail_.To_ = DuTbl.Rows(YY).Item("To_").ToString
                        Mail_.CC_ = DuTbl.Rows(YY).Item("CC_").ToString
                        Mail_.Sub_ = DuTbl.Rows(YY).Item("ItemNm").ToString
#Region "Body"
                        BdyStrt = "<p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:36.0pt;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;text-indent:-18.0pt;'><strong><span style='font-size:19px;line-height:107%;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;'>نظام التذكير التلقائي للمحور التجاري&nbsp;</span></strong><strong><span dir=" & Chr(34) & "LTR" & Chr(34) & " style='font-size:24px;line-height:107%;font-family:" & Chr(34) & "Bahnschrift Condensed" & Chr(34) & ",sans-serif;color:#0070C0;'>Smart Calendar</span></strong></p>
                            <p dir= " & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:36.0pt;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;text-indent:-18.0pt;'><strong><span dir=" & Chr(34) & "RTL" & Chr(34) & " style='font-size:19px;line-height:107%;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;'>&nbsp;</span></strong></p>
                            <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;'>
                                <ul style=" & Chr(34) & "font-size 20px;direction:ltr;text-align:Right;" & Chr(34) & "<span style='font-family: " & Chr(34) & "Times New Roman" & Chr(34) & ", serif; color: rgb(65, 168, 95);text-align:right;'><strong><span style=" & Chr(34) & "font-size: 20px;direction:ltr;text-align:Right;" & Chr(34) & ">"
                        BdyEnd = " </span></strong></span>
                                </ul>
                            </div>
                            <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:36.0pt;margin-bottom:.0001pt;margin-left:0cm;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><span style='font-size:19px;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;'>&nbsp;</span><span style=" & Chr(34) & "font-size:16px;font-family:&quot;Times New Roman&quot;,serif;color:black;" & Chr(34) & "></span><span style='font-size:16px;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;color:black;'>&nbsp;</span></p>
                            <div align=" & Chr(34) & "right" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;'>
                                <table dir=" & Chr(34) & "rtl" & Chr(34) & " style=" & Chr(34) & "border: none;margin-left:-1.0pt;border-collapse:collapse;" & Chr(34) & ">
                                    <tbody>
                                        <tr>
                                            <td style=" & Chr(34) & "width: 97.3pt;border-top: none;border-right: none;border-bottom: none;border-image: initial;border-left: 1pt solid windowtext;padding: 0cm 5.4pt;height: 56.2pt;vertical-align: top;" & Chr(34) & ">
                                                <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><span dir=" & Chr(34) & "LTR" & Chr(34) & " style=" & Chr(34) & "font-size:15px;color:black;" & Chr(34) & ">&nbsp;</span></p>
                                                <table style=" & Chr(34) & "border: none;width:76.5pt;margin-left:.1pt;border-collapse:collapse;" & Chr(34) & ">
                                                    <tbody>
                                                        <tr>
                                                            <td style=" & Chr(34) & "border:solid #DDDDDD 1.0pt;padding:.75pt .75pt .75pt .75pt;height:5.35pt;" & Chr(34) & "><br></td>
                                                        </tr>
                                                        <tr>
                                                            <td style=" & Chr(34) & "border:solid #DDDDDD 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt;height:41.5pt;" & Chr(34) & "><br></td>
                                                            <td style=" & Chr(34) & "border:solid #DDDDDD 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt;height:41.5pt;" & Chr(34) & ">
                                                                <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><span dir=" & Chr(34) & "LTR" & Chr(34) & ">&nbsp;<img src=" & Chr(34) & "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAKoAAABJCAYAAACtpr2uAAAdlklEQVR4Ae1dB1QVZ9qe7G7+bHL238TkPymbTbLZTTZld9PXNE2xgb1rVFATC2piiUlMrNHEGhuiIL33IiIdFVCqIgpILwIiUgRRQEDa85/3G+bemblzLxcRxHPunHPPfP375p3nfuVtw8FwGShwH1CAuw/GaBiigQIwANUAgvuCAgag3hevyTBIA1ANGLgvKGAA6n3xmgyDNADVgIH7ggIGoN4Xr8kwSANQDRi4LyhgAOp98ZoMgzQA1YCB+4ICAxaoBTeuwjU/FtVNN/uOkJ3AoaxQmJ62wIfH1uFvfsswM3pP3/VnaPmOKTCggHq7vQ2rzjhhU4onUqry7/ihuqt4q7UZ46N2gLM2Auc0DZzrbHBuJuAcJ+P7ZJfuqhvy7wEFBgRQE6tyMTxkI5bGWaKzs7PHZLjR3ADPwjgsTrTBsLBNeNZzIQ9Aq+HgbMeAc5yKp7wXYfLxHfgmyYFPI3B6fqn+ecwH5zAZVxprety/oULfU+CeAjXkciqe8DbDpvOePXvSTuBgdijGRP4KznEaONvRDIycyyx+ZnSfC46AJwCRwpTmOgec6yxpnlDGdTaMIn/p2TgGWOn61macqsjWOiqXvGitefcyI6AsVdK9a+EpSZwi9wSoiVV5GOQ+D+vOeWgMSFeCXU4U3jz6vWjJnqMMOgF8+t4JyPaTkFd3RVf3Az7vuyRnPB+wQnGcmbWl4KyGobOjQzH/XiXuSD
                                                                +K530WS7rn9v8Xudel76JfgVrXVI9nvb/C/Ji9koHpihB4Jp7YCe7wSH72dDNVz5T6ArG7cq5zMDZ2n65hqPJut7ei/naTKq5PoK6lAVvSA1jRQZ7zcSgzRJ9qPS6z4ZwnOLsJqFE4gBbWV4A79BnsC7qfVX9IcWN9j4vagRknfuvxOHpSYUP6EXAHPgZEOz7OcjjmnrKQNNNvQB0VtY2dqtv1/EcfLUnCY96LwNmO5Zfs7sDWm3w2o05GSmWehDhKkZCSFKTVFCtlaU1rbruNR9zmwCzRDrFXLoIOjX1x+RUlgLMazjgZ8varWxrA2Y7Dq0e/V2W1dbSjsbVFFRcC/wlYhfGx5vArOI1bbZr5Qjl97nuzI+CQe1xrUb+CU+CsjbE144iqDOc8C5zdOFWcAn0O1IirmeCsRyPssnQfIhmFKBJ4KQmPuJuCs5/I7yt7A8Ce1HUzwT+PrhaNRDm4pmu2Uc7Vnfqou2mvD2uVjbXYdMFbsaOEimxwNqPxpN8yjfyWttvgHKayA+P1rhm3tb0V//b7RqMsJbwbuBqhsr2jYkGFRPPc43jJbwm4A0Mw8eRujRINbc2qtPjyLAbK532XqtKe91sGznoUkityVGl9CtT/hm7A8OB1qs50BU5cyRABdN7dX967Ay3Nqg6TUN5Yq3WYVxtr4VNwWmt+dxkNPdwyiNvLrr2M1wOW41HvRfg8coc4SxXOrCtjQBwdtglZ1y+r0inQ2t4Gznk6hh7fgZ8vHmN511ubwJl/BL9LCZKyFKFZv7WjXSNdW4JTfgxe8f+aLePTY/Yj+5ryqkMztE1OpKqZKw3XwB02wnMBy1Hf3MDS3z/2I4yjtsH4pHrb0SdALb5Zyf7ZUeUZqgFpC1xtqMFz/t+AsxvfvzOoEnDtJuBMtXb+bWR5OpKuFWh7lD5LP5AVjmERm3G6PAtfJ9tL9nPiTiua6sAdHgVoYfE95G6CoLJz4ip42nsBng1YJUnTN3Io7yReI3BaDMGUk78hQ48t0W/pgZLmrzc3gNv3X0na5+GbsSDhsCTtrgN1W6oXOOcZkk60Raae3A3OxhhcXxyQlIDYXZrDRNDMru06UpSIy
                                                                lvXUdtcr60IS3cpPA19/qQ6GwGQeq0Ik6J2wjorrLuiLL+mpZEtowW10tlUqPycrxksskKFKLvvSDvC3sH1phuSdG2R/TmReNHHDNy+wRgdsRlnK7X/sZXa2H1BvRcV8rm976Cq4boQxZxT5jCK3KqKU+CuAvXlo6vxpR4ner+ieHD2E8C5fNH/S7wusNqNR3ptiYRA4shvGYGYEL0Hu9Oks4K4zBNeX4Ez/wAPuZuKk/sl3NJ6G5z9ZJyqyFLs76WA5dh83keS19jaDO7AUFjlaT/wUIU50fvA7XwNQ0LWIvJKuqSNnkQss8LR0t4qqcKZv49zVeqVakWKMz6UbRnvGlA5h4lwLIyTDEAp8mrQ9/wyT3tCXaDp7zwaj9N0VNxS/7Pl4y9rrsMgz69Q2nBNnsXiD7jMxGuBq3GhqgARxWcUy/RpYifwkNsc+JWeVezm3eA1WJHkqJH3ZtD3mBW7XyNdSKhrbcLWNJ69JqTd6f1ln0Uwi7OSVKcTvl9xoiptS1YwnvH4ShWnQK+B2tnRCc7GCHk3rkoalkdirl5kG30mV+9vEOrTn7spXjmyUj5svePDIn/F4GNr9C7fm4LVzTdhHLUd7wX9iGjZOWCQx3y4F8YqNj8iYhMWx0n3flRwf2YIHvf4UrFOTxKb2luRWlPUbRVii4mvQe5zsSdbvb0JKT4DznGKuEjvgNpELI8DH4I2xLquiTH7efl6d7OoxzxeBEqiUNoWkHiUfs4z+TiJQfUB3Z2UcZ6BuQk2Wh+jta0VpjImtFC46GYlHnOfK0QV7+evdf8CFSvKEjNqLoE7OBSc5We8EMRqJI5eSlKVes5vCcyzlAUKw2PNYRzxq6qsEKglHuthYyF6x3f77Cg85SmdCcWNWWVHYE2KptLPP3yWYl2an6ro2ap8Jn1UJfRmRr1JrA2Lod1KaZ7x7lIQUQIPAZfk7w5T2MD+6DobHwSvZcol3573wfasYNhmR8AiJwI7s4Lx1rE14IjHqtRWr9Lmg7ObiLwb5WLaSMIk0XHMV5bq2GRHYHSUdPMvrlzWcA1P3IUZq67lFriDn8A6O4JvvrOTp4XLTFV3/wlajb2ZQaq4
                                                                OLD6jAteD1TmFf+fxzzkazmEidvQFT5bkQsSf5bX81sjVxkrb2GSDR73WqjRxNtBa7D0jHpLUlB3hWFLXPCOlv6OtlZ2YKjSwXO8eP0Kvxd1m6MJLFKps5vApvcpJ3YisDhZPCaNcM7NCkw68Rs/23Y3K98JYN1NQQcNXZdJjDkyb5QpFnEpPMUIy9QG7SbjQbc5+L3LLOzNDGblSxqqwVmNwO4MZQApNipKDC7h95wv+i6BV750WS+rr5ZIcT4KXY8X/b7BkJD1+CmVV/apbb6BkNIzsLwYjMd9FolaVgef9lqEA7lq/qY6p2ehIcE/4VgxP14S9ESUnVc18ILfUkWOkFHUVsyNs1SVu0342i9lWd0RUOmUllJ7SdWwPBBUnMyznWgpFwOHlnTLYRgathFJOrR8hPYCSs7gKd8lvBiVwK0LpLryxGNQCtuNh48C01sYB93fC/oBTS23xEmScGBxEoaHbcbjdOqnP6fzDDzhp5a2jI3aBs5mDL47p7+m2JmqPPyPyxfwLjyFI8WJMDquOWsHXErEo14LMC/OCiQjJ6EFozndrY0ZX3hj2hGk15TAJ/ck/tdLc2nemxnKthFi8ark4fSMkLol5zhJpappfHwnONvxbJXkDn2KN4/+gL/7mGm0Nit2H2bESHUtuH3vSsr1GKic9UjYa1kCqeVtKZ6M2c95iHQ9CaDWRjBLsAY6RNoHkqGoIzbZ4TzB7Sfrv9Q7zWDgkPSrBEp5mvtcPKVAPPVo+NC/fBbjVg8kS+vT/PGFiPhRV9LZzEczKwk3FsRbwS73BBLLM5FalY/kq9kIKz6DnzOOYGzkViZ25sw/xB/d52Jo+GZ8ELJWNaTaWzewLc0fnON0vpy1MX7nNAMb0vywLMGG7edjSs/jac/5aLrdjIkRvPqiW34MhgZJD3yhl1MZT/RUeQb+180E68/yCimqzvQI1DbVY3zMXhA/1Chym6pGOu2nbUaDZPckkqXrvcBvkVVbqipDAbNke5icPihJo2cXXz0C6itHv9NgxIobWxZvzS/3AhhoFjxshCk6WB/i+kKYAdXaWDobC20q3e3GIa26EDtIE4dmkp7Mrnbj4F/
                                                                YvVh0kOc8CQtFGKv8XnSjAn/1X8aW+nqRQsfNllv4p/9ynK/Kx6iILTzALIaCO/QJfzCy/JQPW3zCDo9zT5njakMt6m/fYjMjzdAqYB6kOp+zrdPc0xYS9UQSfZKlAkl75sRZovxWDdad48FnnRWOXzLUbKZdRC/zwViV7MQeI6U6H9z+D/CY90LY5kWhsUVTS6yjvR0F10qxLzMY8+Is8AdXE7YNpGXeLf+knBxMV1icODV2H/7sMR8tt5vR3tYGn+IkRqt8GdeIgNrZeltVVW+g7iIJhu0YVUV5YHmCLc/EJyDRkm9tjA/D1qNZQTtHXlcp7px7gokDmcKzEjiFNPe5eMZ3iaqJRYm2PJdAyNd1dzfFs/5fq+rqCmw578sUJXK1HDgSK3Px6tHv+L2q03RUyyQ9u9IDMEWmoHGzuQFnKnJw5FIiIorPIqtGWdgw4/RBTIjajs/CN2NGzB6YZwbj8s0qXcNFUR1/MHTOi4FfKS82DS3h7+3t7Xgj+CcQGH5KcZe0U9N0A4O8FzCZPYlGackmsSxxBTj6E1l8xHMduv4sn4VtgreIByppDMDL/lKll9qmG0zkyto6MATcnrex5ZyXvBq/RxVp2ukF1KL6SnC7/gU6vSpdG866qWdSYiU5TsXdYMdk3rjKGNjUntZZ0n4iPGQHjN8xDX/Z/lgJsHbjcbwsTemRFNPYC7T8DJ+G/4yDWWEwzwrFl3GH2D6MsYxsx2GDTPJDDU2N3sNmuPM1hYrtdpfoUKA5U3VXR8inve04gSPR0YmFcZbsnEDgi7gslfsLdehOWlokRVqa7ASzhMNYlmSLled94JYXjZgr6WhuVWtAieuJw28cW4Mxx7eLk/hwRwfj3RK3pK1NWeWRlGXEl15AJZ1Q09PqU5m4AZ+CWP6wQ8utzWjMjpZuisVl7zS88qwrz4elP4F4WfeYhz8p8C8X0sGC9sVK4BTSGCtMP80u8bgXxVuBsxkL7sBH4Cw+BmczDkNDN8FLYftgnh3BCzkOfoaD2eHiZmASZ4nAbg5wkgp6RDo6O7E+xR1Vt+okpRmHhezHLIexbcaorj2rpNBdjCRV5fI2awc/lShxVz
                                                                ToZ49W01IPo/ANkhF1C9Sppw6AO/S5pJIQKamv4vdPxAu1G4/wikwhq0/uK844grOdwB9KnKazU/Te9KMafTnnn+RtqARQyu8EdlLp07JCaDTYw4T1qd789sNyGB5wmYVMmf5Ae0c7tqT64GqjdnFtT7o8nBOJF7wX4+Og75CgoPzd0NqCRQnW+D7FFTV69HkgOxQueSfYEKZFbe9WCUcYa/q1S4xPS0KgP3vMA1n7CtfGc15sL2ufEyUkab3HXc3CZdm70QnUorqrbK+yO01T44V6YYx6h8n4mxY7Ha0j6WVGZk0xdtBmPskWbQoqbccun+VnMjlAhbjdePycrvxMdzq0oJIz+Ch0A3/IsR7FFL8tM6WaSuK2d2qhqbhMd+ExoevxpMc8HNZTu6q79ij/cmMtO1CR4vKS2ENMwEDnDV2XXUEsHvP8il9h7MaBuAvya8/FEHB738UxHdsNeR1xXCdQH6HO7caLy6vCw+jkajkM3yTYqtIGSkAnUN3m4F9apDM9GX9tcwN2pPnjFV8zcHve5F+S9Vh8ELJOL+7A5lRlLX19x1Df2oQK2RKvb93uyiVUZmNDsjMrtvasK05V5mpUCSk9x3RkuYOfsgPkA+6mEoVojQoAGm5r50MrlRenaQWqPzHtrY3wZaKm/DuuuhDc7jfhovDPETd+r8KOeVqWflry7SehupcvOL2mmM0atESR1v+dXO2dA8saVJ9nSK7Kw85zvngvaA1GhK3HogQrrE/zxblqtYqePu3cSRmtQGV8u8MjQSwU+cVZjQQNeqBe3yY5gnOZqXmYshkDj0vxA3XYhnHpoIAiUANKU9iS/4LI4Epow68wHrGV2p0cCOXu5f1ZMm2RK684TIZZvKaK270cp6Fv/SmgCNTXA1YxJWKzZLVGi9Bk9wJQoeS9uZc0VHWJUkWK2S5f4G2RmfC9GZmh195QQAOo9c2N4GyN2Yk+uuxCb9q+J3VHHN8hNXEheyy3Ob0eS/6NcsYOYyY0ZMpt+PUtDQ59jiiR5pUGUFeluPDMcpvRaBLxwXr9pvuhgdSaYib/VgkFSELlNE0vKUp3wyPvIwsTbbAwyQ6LkuwNvz6mw
                                                                azTFsi/qbYa0QDqX0mtjl7w4RHdvbsBl/+892JeZ5X4pe7zGFOfRIGG6/6ngAZQSQuGiR5lLlUG+qMuJKUY8nUqgNRuLEpvVgz0YRvGpycFJEBNKu8ywKOXTY4M7pPLMz+G3y+RDiytBvYTUNqNdtF98miGYXZRQALUnRePgSMFZAKqtdF9QaSkiixevZCY+XRwcpyKah0mz33xUNXNN0AaZvpcbgWxICvSu335FsXjmpbnDi85N2D43h0dHbjWpQK5JonXg1WixdpEXjIm5EmAuiLJXq11ZDcelwa4v9DkyhxevZBASh6kXWagtU2tbCs85N26r4q1xOCAb/FXjwV43WsJXvU2w0OOM9jqc6RE047/YGYoHnM1wd/9V+IPTjMxMmwj5sda4NLNSpTWV+MFt/kY5GqCSeG/Ml9PpLbw7WkbjAneiAcdZyK0+Cw2JznjvYBvmZ37a95L8DePBUyB+u3AVTgtEm2SXilt255wMcE/vczwlOcC/MNrCf7sYsK8+JG+rPxqar+NSSGbQe0+47EA//Fehr+4kcLOVBhH/qLVuji5Oh8v+ZrhEbe5eDpgBTOBmRyzB+QAQ35Rvw86TsWTfsuZRfGnEb/AIZdXeCHNM9IXeclzEZ72XIgnPb5i1gDkdfBxL6ltlwSoJrHm/AunGdV5JjaJTFjlA7jX8RAS8ZJLSgKp0zQ8LlKe7sux7b4YxFQOyVRcuIaEbcRhkV06pb/qvxyDg38SirA7ORIjUxQyr6arkczN7SdgSOhGSTlSJTwuYg3uzAhkW5sWkRJ6NPlJOPgJvj/HKz4bnfwNR0t4I8mI4hRmA1VazytXz4k/DGcdErnhUb/iQZnDh82k/b/nLSRWqj3q0SDnEUasjSB+fkp/gxyLmH+Ak+VqLyrljTXg9ryBiyKHbU/7mqmsaH/nZqJ6bs5lOt47pqYXibrFlwSo805ZqIHqbooXFNwXiivfq/BPpJ9KOqG0J7Ubh5nHd/XbULalBbA+xb7+w66kYesFtV36lOi9eMBd/RLEgyMHYGKl8nU0E1oOR2yXIwnSXnpDpjTzS5of01Eok+27yaqVHByTmcuwsHWqfblvXgxT
                                                                vySbJbr8LyVgrQ53mcMit7Btk3icFP44fDMTRQvp2y74Mu0wIS6/v3BkFbhDw1T6D9su+DGrCHG56LJ0mJ1xwO32dgwN+k6VRRPjW0d/UMcdp6nCFJAAdSV9iEHsD8p2LEilbiBd/ybX6OQHgJm7jMJ+Lc4W+mrMAlDJ1IT8AFhkHEPctQKYRJuzLouZG8VRsMlWNj1emewMn7IU1fCayMbJaSqe7zKJmRy1DQmVUt9RAlCvyIB6ofYS8yLtUBgLcmkpaDz65sVKgEq+/XW5vNQGVHP6I9iMxuWumZmzHIENMtMV1YMAKCC3l1bDMbXLXWRwURL7I/10Ru10IruuDAe7nPaWi3RjSTdDDNRCmY8FCVB3ZYcxH5oqzXj3uXjYc754LPcs7E+O1cg1JZki0wcjHKegSMQQ7q+B8UDlVR/JDeWmVN7pWGsHb1Jhl3uczTrxWtxTxlfnIb1O6h9gM808NkYg5WK5czB6Lm1ATWdA/RS2MnfncqB2RxttQN2bFsiAStpmAQVxjLd+7Ipu052H6UDrMkvV5R89F7CtwuAwqca+qkBXQD6jauSLE8hTBjNboD2q8HOahq/jNVX9xPX6Mkzekf9xZGUX+4nMXcZieNjPfdmlzrZ30NLvMBmP0qHD/EMckiktb0wms5lxEqkKm+pkZuLks0t1dYLZ5tM2plCBe6ANqD+c92EzltyW7W4B9d2QdWxSoHEyqwXbMSi4Lv2TqZ6hK/Bx6EYNI9B3qB0yE7cZg6OX1M7QxHXlM6o4j8KSGZUl0KxFBxQBqHS3GQ3zDN5LsbyBvorTv3gUfZ6HvhNFmlAus9mM6tWNV5W+Go/QrnhGpQPNxlSpBeXWVB+QGmR8l0PgssZavOm3FO8HrsIfyJSbrDftx2NUyI8Sd0gfn9iJP3kqOypjQHWYjEaRAwxn8n1vMQR7MjRNce4IqO7zhEdk96/Jmnf/YFy4xu9z91wIYDg4dkW3/sfHZOVgP1HSFkWOXT7P/sC0pyZrCPnVY6CSPbmixz3bsfi+H7T5L9WVgw4czMEv2WJ1mV5/FLZJ/mz3JC7eo+bUXcaOVF82jriKTOTUFjMHvmT5YCdy/y0
                                                                eKPnaUjKUHBy1DQ97zFP8vM5WcjbhMBnv+q3Ev32X4wmP+cyJbrYW9mFPgToi6hf2zj8M+A6vey3FMx5zMfv0IbSLPopB/kvJl8Bm2R9T/GwUftjdFG91aaoZy7gZbeSqh84XCkDu0dJPHdHgCPWSGVWYXZ2m4fduJjhffWdmv/KHEuLkKc/8YhAepf0MsZyY+54v+YdynaXBIhHq3Yu7ANSrt2pB7hPLGnkT8j0ZgfDrYgHRHu1pmT07jZUcLtCLnCbyoCI8gy6g8jPqFL09tfQUqGyPKptRhXGJ7+yg7SQ9jYvziR1G3lKiu4w8X1Hwc/VNsgP73pW4HoV7PKNSpU1kp0/uHgWAiu+k7GE7Fs94L4Y5fbRA5CRA3rmueFp1AVafdcZTPot5S1ayKiXxJ/VFXkFsxoBe/kC7dqUHMvbU9Rap5YPp6UMIucq7VT+UE8mMIncpfE+KZpPJ0Zrf2Xo/6lc84qF8cN2Wzu+LK/U0Nw7Mj2M0zb4udZ2jjZZsRnXT7TaT6qZWF7DtxjvhmxWboll/dizP/aACQ0LXw0HmPWVS9G42NnkD9Cd4R+ZuSFxGY48qZD5Gzr5o6RWDVBwmUBGgrEfiGW8zTIvejQ0XfOGRHwNykhZ/NQtkUxRSchYOOVH49pwHxkdtw198ljLeGu8afZYanLQvZgAdDeItDsSLfD6ZEK/ZagTzwOycHwP6zSNXRlYjUSRSgiHnCrTHG3NiJxIrspml6MNO0+CUE4Vv4tUGkfSxjfpbN/H3Yz8yNlXetRKUi9hQN5vqMZv6tByO8OKzEhNkOY3Ifou+lbWa2IyWn8M+OxLJlbkazHl1vU5cqavEi2QRYT8Jl29UoLldLchQl1OH8sklpO1YPOA0Hb5FCcy79ibamlh+hm0y5xszCZRWI7A2xZ3511oUd5j5uUoVCQAu11XgWsN1ttV7ynsxGm7V46rMVJp61wpUynyQeKryj9uKwSqECbRUrstLCrGO6N9F7tJZmLSaWFtz1MBU1TXlyzpOwcYeeLpTk67/Qvuzw0DspyPFSYxPSp5E6OeeH4s5sebIUnD3Q6bDC844YbfoIw+zRLPOzqww9iIts8
                                                                JgmxMF+vreepHwwCr3OGxyo0DeArdnBCJeQRQqUOBibSm2pPnDJicKR4uTcSArFLsuBuFmS6NQRHK/3dGGX9MC4FUYB9+iOGxPD0RpQ7WkjLbIhWuF+Pm8D0yTHTQ81Qh1ViTwLtAdc09gdqIdLDPVXqWFMmsv+GF9igeoDH3W58ezbjiUo/k9AZ1ApcaeJVkuabPLOQEC0O7kTsAm4Fob42X/FXDO1/xIq/AghruBAkSBboFKhWxzIhjTlul7yo3m9AEqgbzLZygd1Mib29oUV9Td0u+TMYZXZaCAXkAVyHQgM4TNgCQmY+4dnb/gta1o2WcSI5IakRbTLF5dkNwfWhux/c/w8M3YnhEEsWKF0K7hbqBAdxToEVDFjcWUZ2D9BW98GWeJ6Sd34/OwnzEhchtmxuxjnt/WpfnjZOl5NIiY1OL6hrCBAj2hwB0DtSedGMoaKNBbChiA2lsKGur3CwUMQO0XMhs66S0FDEDtLQUN9fuFAgag9guZDZ30lgIGoPaWgob6/UIBA1D7hcyGTnpLAQNQe0tBQ/1+oYABqP1CZkMnvaWAAai9paChfr9Q4P8B8iy0gQVAT5kAAAAASUVORK5CYII=" & Chr(34) & " style=" & Chr(34) & "width: 66pt; height: 55.5pt;" & Chr(34) & " alt=" & Chr(34) & "image" & Chr(34) & "></span></p>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td style=" & Chr(34) & "width:305.1pt;padding:0cm 5.4pt 0cm 5.4pt;height:56.2pt;" & Chr(34) & ">
                                                <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><strong><span style=" & Chr(34) & "font-size:16px;color:black;" & Chr(34) & ">نظام التذكير التلقائي</span></strong></p>
                                                <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><strong><span dir=" & Chr(34) & "LTR" & Chr(34) & " style=" & Chr(34) & "font-size:15px;color:black;" & Chr(34) & ">&nbsp;</span></strong></p>
                                                <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><span style='font-size:16px;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;color:black;'>البريد الإلكتروني<em>:&nbsp;</em></span><em><span dir=" & Chr(34) & "LTR" & Chr(34) & " style='font-size:16px;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;color:black;'>&nbsp;</span></em><span dir=" & Chr(34) & "LTR" & Chr(34) & "><a href=" & Chr(34) & "mailto:" & My.Settings.MailUsrNm & "@egyptpost.org" & Chr(34) & "><em><span style='font-size:16px;font-family:" & Chr(34) & "Times New Roman" & Chr(34) & ",serif;color:#0563C1;'>" & My.Settings.MailUsrNm & "@egyptpost.org</span></em></a></span></p>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;'><span style=" & Chr(34) & "font-size:15px;color:black;" & Chr(34) & ">&nbsp;</span></p>
                            <p dir=" & Chr(34) & "RTL" & Chr(34) & " style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:" & Chr(34) & "Calibri" & Chr(34) & ",sans-serif;text-align:right;'><span dir=" & Chr(34) & "LTR" & Chr(34) & ">&nbsp;</span></p>"
#End Region
                        Mail_.Body_ = BdyStrt & DuTbl.Rows(YY).Item("ItemNm").ToString & " يوم " & DuTbl.Rows(YY).Item("DuDate") & " متبقى " & Int(DuTbl.Rows(YY).Item("DuDate").Subtract(Now).TotalDays) & " أيام" & "<br>" & DuTbl.Rows(YY).Item("Details") & BdyEnd
                        If SndMail() = Nothing Then
                            InsUpd("update main set LstSend = '" & Format(Now, "yyyy/MM/dd") & "' where main.Sql = " & DuTbl.Rows(YY).Item("Sql"))
                        End If
                    Next
                End If
            End If
        End If
        If Weekday(Now) < 6 Then
            Dim Hour_ As Integer = Format(Now, "HH")
            If Hour_ <= My.Settings.Hour_To And Hour_ >= My.Settings.Hour_Frm Then
                If Format(Now, "mm") = My.Settings.NtfEvry Then
                    If GetTbl("select [Sql] ,[ItemNm] ,[Details]  ,[DuDate]  ,[Wdays]  ,[To_]  ,[CC_] ,[LstSend],[Ignore] from main 
                                     where( main.Ignore = 0 or main.Ignore is null )  and Cast( main.DuDate - getdate()as smallint) <= Wdays", DuTbl) = Nothing Then
                        If DuTbl.Rows.Count > 0 Then
                            For YY = 0 To DuTbl.Rows.Count - 1
                                NotifyIcon1.ShowBalloonTip(0, "", DuTbl.Rows(YY).Item("ItemNm").ToString & vbCrLf &
                                                                  DuTbl.Rows(YY).Item("Details") & vbCrLf &
                                                                  " يوم " & DuTbl.Rows(YY).Item("DuDate") & " متبقى " & Int(DuTbl.Rows(YY).Item("DuDate").Subtract(Now).TotalDays) & " أيام", ToolTipIcon.Info)
                            Next
                        End If
                    End If
                End If
            End If
        End If
        DuTbl.Dispose()
    End Sub
    Private Sub Hidden_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ContextMenuStrip1.Enabled = True
    End Sub
    Private Sub CloseToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles CloseToolStripMenuItem.Click
        Environment.Exit(0)
    End Sub
    Private Sub FfffToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles FfffToolStripMenuItem.Click
        Main.Show()
    End Sub
    Private Sub Hidden_FormClosing(sender As Object, e As FormClosingEventArgs) Handles MyBase.FormClosing
        NotifyIcon1.Visible = False
    End Sub

    Private Sub SettingsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles SettingsToolStripMenuItem.Click
        Settings_.ShowDialog()
    End Sub
End Class