'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PostOff
    Public Property OffFinCd As String
    Public Property OffSector As String
    Public Property OffArea As String
    Public Property OffNm1 As String
    Public Property WorkingDays As String
    Public Property WorkingTime As String
    Public Property WeekEnd As String

End Class
